services:
  - type: web
    name: ubs-fastapi-backend
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: DATABASE_URL
        value: postgresql://conversion_db_user:cfT1YV89IKhP1UJyAXIzyDI6oxoMV8x0@dpg-d1t74v3uibrs738vu1tg-a.oregon-postgres.render.com/conversion_db
